package main

import "fmt"

func main() {
	fmt.Println("Day One")
	fmt.Println("--------")
	dayone()
	fmt.Println("\nDay Two")
	fmt.Println("--------")
	daytwo()
	fmt.Println("\nDay Three")
	fmt.Println("--------")
	daythree()
	fmt.Println("\nDay Four")
	fmt.Println("--------")
	dayfour()
	fmt.Println("\nDay Five")
	fmt.Println("--------")
	dayfive()
	fmt.Println("\nDay Six")
	fmt.Println("--------")
	daysix()
	fmt.Println("\nDay Seven")
	fmt.Println("--------")
	dayseven()
	fmt.Println("\nDay Eight")
	fmt.Println("--------")
	dayeight()
	fmt.Println("\nDay Nine")
	fmt.Println("--------")
	daynine()
	fmt.Println("\nDay Ten")
	fmt.Println("--------")
	dayten()
	fmt.Println("\nDay Eleven")
	fmt.Println("--------")
	dayeleven()
	fmt.Println("\nDay Twelve")
	fmt.Println("--------")
	daytwelve()
	fmt.Println("\nDay Thirteen")
	fmt.Println("--------")
	daythirteen()
	fmt.Println("\nDay Fourteen")
	fmt.Println("--------")
	dayfourteen()
	fmt.Println("\nDay Fifteen")
	fmt.Println("--------")
	dayfifteen()
	fmt.Println("\nDay Sixteen")
	fmt.Println("--------")
	daysixteen()
	fmt.Println("\nDay Seventeen")
	fmt.Println("--------")
	dayseventeen()
	fmt.Println("\nDay Eighteen")
	fmt.Println("--------")
	dayeighteen()
	fmt.Println("\nDay Nineteen")
	fmt.Println("--------")
	daynineteen()
}
